from ArrayStack import ArrayStack


stack = ArrayStack(20)
print('Is Stack Empty? ', stack.isEmpty())
print('Is Stack Full? ', stack.isFull())
print('Length of stack? ', len(stack))
stack.push(4)
stack.push(5)
stack.push(4)
stack.push(3)
stack.push(8)
print(stack)
print('Length of stack? ', len(stack))
val = stack.pop()
print('Value removed from stack? ', val)
print(stack)
val = stack.pop()
print('Value removed from stack? ', val)
print(stack)
val = stack.pop()
print('Value removed from stack? ', val)
print(stack)
print('Is Stack Empty? ', stack.isEmpty())
print('Is Stack Full? ', stack.isFull())
print(len(stack))
